services:
  app:
    image: ghcr.io/veredianerodrigues/cartilha-react:latest
    container_name: cartilha-react-app
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - .env
    volumes:
      - cartilha_db:/app/server/data
      - cartilha_uploads:/app/server/uploads

volumes:
  cartilha_db:
  cartilha_uploads:
