services:
  app:
    image: ghcr.io/veredianerodrigues/cartilha-react:latest
    container_name: cartilha-react-app
    restart: unless-stopped

    expose:
      - "3001"

    environment:
      NODE_ENV: production
      PORT: "3001"
      HOST: "0.0.0.0"
      JWT_SECRET: ${JWT_SECRET}

    volumes:
      - cartilha_db:/app/server/data
      - cartilha_uploads:/app/server/uploads

    networks:
      - traefik-public

    labels:
      - traefik.enable=true
      - traefik.http.routers.cartilha-react.rule=Host(`gravidezadolescencia.com.br`)
      - traefik.http.routers.cartilha-react.entrypoints=websecure
      - traefik.http.routers.cartilha-react.tls.certresolver=letsencrypt
      - traefik.http.services.cartilha-react.loadbalancer.server.port=3001

networks:
  traefik-public:
    external: true

volumes:
  cartilha_db:
  cartilha_uploads:
