// Gerado a partir de um backup completo do conteúdo em produção
// (capturado em 2026-08-05, antes de identificarmos o bug de montagem
// do volume Docker que zerava o banco a cada restart do container).
// Este arquivo é a fonte de verdade completa: árvore de seções + blocos
// de TODAS as 19 seções, não só as 3 pilotos.

export const TREE = [
  {
    slug: "apresentacao",
    title: "Apresentação",
    pageLabel: "04",
  },
  {
    slug: "adolescencia-chegou",
    title: "A adolescência chegou... e agora?",
    pageLabel: "05",
    children: [
      {
        slug: "transformacoes-menino",
        title: "Que transformações ocorrem no corpo do menino?",
        pageLabel: "06",
      },
      {
        slug: "erecao-ejaculacao",
        title: "O que é ereção e ejaculação e quando acontece a primeira ejaculação?",
        pageLabel: "07",
      },
      {
        slug: "tanner-menino",
        title: "Estágios de Tanner (menino)",
        pageLabel: "08",
      },
      {
        slug: "transformacoes-menina",
        title: "Que transformações ocorrem no corpo da menina?",
        pageLabel: "09",
      },
    ],
  },
  {
    slug: "menstruacao",
    title: "E a menstruação... o que é e como acontece?",
    pageLabel: "10",
  },
  {
    slug: "fecundacao",
    title: "Sobre a fecundação... o que é fecundação e como acontece?",
    pageLabel: "11",
  },
  {
    slug: "metodos-contraceptivos",
    title: "Métodos Contraceptivos",
    pageLabel: "12",
    children: [
      {
        slug: "classificacao-metodos",
        title: "Como são classificados os métodos contraceptivos? Todos eles são indicados para adolescentes?",
        pageLabel: "13",
      },
      {
        slug: "metodos-barreira",
        title: "Métodos de Barreira",
        pageLabel: "14",
      },
      {
        slug: "diu",
        title: "Dispositivo Intrauterino (DIU)",
        pageLabel: "16",
      },
      {
        slug: "metodos-hormonais",
        title: "Métodos hormonais",
        pageLabel: "17",
      },
      {
        slug: "mitos-anticoncepcional",
        title: "Mitos relacionados ao anticoncepcional hormonal",
        pageLabel: "22",
      },
    ],
  },
  {
    slug: "direitos-sexuais-reprodutivos",
    title: "Vamos falar sobre direitos sexuais e reprodutivos?",
    pageLabel: "23",
  },
  {
    slug: "gravidez-adolescencia-mudancas",
    title: "Gravidez na adolescência e mudanças",
    pageLabel: "24",
  },
  {
    slug: "orientacao-quem-pode-ajudar",
    title: "Se eu precisar de orientação, quem poderá me ajudar?",
    pageLabel: "26",
  },
  {
    slug: "referencias",
    title: "Referências",
    pageLabel: "27",
  },
];

export const SECTION_BLOCKS = {
  "apresentacao": [
    { type: "paragraph", body: "Ao longo da vida o ser humano passa por etapas, marcadas por transformações que constroem seu jeito de ser. Uma dessas etapas é a adolescência, na qual ocorre a passagem da infância para a vida adulta, momento em que mudanças físicas, emocionais e psicológicas são naturais. Nesse período algumas atitudes, decisões e ações podem marcar a vida toda. Você sabe em qual período da vida acontece a adolescência? Será que você está vivendo esse período? Será que já passou? Para o Ministério da Saúde adolescência vai dos 10 aos 19 anos e de acordo o Estatuto da Criança e do Adolescente (ECA), a adolescência ocorre entre 12 e 18 anos de idade (Brasil, 2017), além da idade, os aspectos sociais e psicológicos tem influência sobre esse momento, pois cada pessoa apresenta mudanças corporais, afetivas e de desenvolvimento de acordo com sua história particular, ou seja, cada um no seu tempo, poderá passar por algumas transformações. Na adolescência, juntamente com as várias transformações surge o despertar da sexualidade, que faz parte do desenvolvimento humano e manifesta-se por sensações e sentimentos. É natural que nesse período aconteça o namoro e a iniciação sexual, no entanto, quando os adolescentes têm dúvidas sobre as transformações do seu corpo, sobre as possíveis consequências da atividade sexual sem proteção, ou de forma precoce e imatura, pode acarretar conflitos e prejuízos com implicações em seus projetos futuros. Conversar sobre a adolescência, sobre interesses, emoções, namoro e, também informar-se sobre as transformações corporais que acontecem nessa fase é importante para que quando ocorrer o início da vida sexual, seja de forma consciente, responsável e saudável. Esperamos que as informações a seguir ajudem você..." },
  ],
  "adolescencia-chegou": [
    { type: "image", heading: "O Que é Puberdade?" },
    { type: "paragraph", body: "A puberdade é uma fase natural do desenvolvimento em que o corpo passa por mudanças físicas e hormonais, tornando-se capaz de se reproduzir. Ela ocorre entre os 8 e 13 anos nas meninas, e entre os 9 e 14 anos nos meninos, durando cerca de 3 a 4 anos. É o momento em que o corpo começa a se preparar para a vida adulta." },
    { type: "paragraph", body: "Castilho; Mattos; Pedrosa (2024); Sartor; Fiorin; Sulzbacher (2025)." },
    { type: "image", heading: "O que acontece no corpo humano nesse período?" },
    { type: "paragraph", body: "O comando para as transformações presentes na adolescência começa no cérebro. Uma glândula chamada hipófise libera dois hormônios: o LH (luteinizante) e o FSH (folículo-estimulante). Eles viajam pelo sangue e estimulam os órgãos sexuais. Nos meninos, os testículos passam a produzir testosterona (responsável pela voz mais grossa, pelos e desenvolvimento físico) e a produzir os espermatozoides. Nas meninas, os ovários passam a produzir estrogênio (estradiol) e progesterona, hormônios que atuam no amadurecimento dos óvulos e controlam o ciclo menstrual." },
    { type: "paragraph", body: "Brasil (2017); Krishna; Witchel (2024)." },
    { type: "callout", heading: "E tem mais...", body: "Os caracteres sexuais primários correspondem aos órgãos do sistema reprodutor presentes desde o nascimento. Nas meninas, incluem os ovários, as tubas uterinas, o útero, a vagina e a vulva. Nos meninos, compreendem os testículos, o pênis, o escroto, as vesículas seminais e a próstata. Durante a puberdade, esses órgãos amadurecem e ocorre o desenvolvimento dos caracteres sexuais secundários. Nas meninas, destacam-se o desenvolvimento das mamas, o aparecimento dos pelos pubianos e axilares e o alargamento do quadril. Nos meninos, ocorre o aumento do volume dos testículos e do pênis, o aparecimento de pelos faciais, corporais, axilares e pubianos, o aumento da massa muscular e a mudança da voz." },
    { type: "callout", heading: "Portanto...", body: "é importante entender a puberdade como um período relevante de transição e transformações físicas, fisiológicas e emocionais da vida de meninas e meninos, destacando que nesse momento o corpo do adolescente ganha algumas novas funcionalidades, principalmente no campo da sexualidade." },
    { type: "paragraph", body: "SBP (2023a); Krishna; Witchel (2024)." },
  ],
  "transformacoes-menino": [
    { type: "paragraph", body: "Nos meninos, a puberdade é marcada por diversas transformações físicas. Uma das mais evidentes é o estirão de crescimento, período em que ocorre um aumento acelerado da altura, com crescimento médio de 8-9 cm/ano. Esse crescimento costuma atingir sua velocidade máxima entre os 13 e 14 anos e desacelera progressivamente até o final da adolescência. O maior ganho de peso também ocorre, em geral, por volta dos 14 anos." },
    { type: "paragraph", body: "O primeiro sinal da puberdade masculina é o aumento do volume dos testículos, que geralmente ocorre entre os 10 e 11 anos. Em seguida, acontece o crescimento do pênis e o surgimento dos pelos pubianos. Entre os 12 e 14 anos, começam a aparecer os pelos nas axilas, no rosto e em outras regiões do corpo. Nessa fase, também aumenta a atividade das glândulas sudoríparas, o que favorece o suor e o odor corporal característicos da adolescência. É ainda durante esse período que as ereções espontâneas se tornam mais frequentes e ocorre a espermarca (primeira ejaculação)." },
    { type: "paragraph", body: "Bacil et al. (2020); Krishna; Witchel (2024); Graber (2025)." },
  ],
  "erecao-ejaculacao": [
    { type: "paragraph", body: "A ereção é o enrijecimento do pênis causado pelo aumento do fluxo de sangue nessa região. Na adolescência, ela pode ocorrer em resposta ao desejo sexual, mas também é comum acontecer de forma espontânea e involuntária, como parte do desenvolvimento normal do organismo. Já a ejaculação é a saída do sêmen pelo pênis. O sêmen é um líquido esbranquiçado que tem a função de nutrir e transportar os espermatozoides." },
    { type: "paragraph", body: "Como mencionado, a primeira ejaculação do menino é chamada de espermarca e geralmente ocorre por volta dos 13 anos, embora possa acontecer em idades diferentes. Ela pode ocorrer durante o sono, em um fenômeno normal conhecido como polução noturna, ou em outras situações. A espermarca representa um importante marco da puberdade e indica que o sistema reprodutor masculino está amadurecendo e adquirindo capacidade reprodutiva." },
    { type: "paragraph", body: "Krishna; Witchel (2024); Graber (2025); WHO (2022)." },
  ],
  "tanner-menino": [
    { type: "callout", heading: "Você sabia...", body: "A puberdade ocorre em diferentes fases, que refletem o grau de maturidade sexual do adolescente. Para avaliar esse desenvolvimento os médicos britânicos Marshall e Tanner desenvolveram uma classificação conhecida como estágios de Tanner, utilizada até os dias atuais pelos profissionais da saúde. Essa classificação permite acompanhar o desenvolvimento físico durante a puberdade, pois adolescentes da mesma idade podem apresentar diferentes graus de maturação sexual (Marshall; Tanner, 1970)." },
    { type: "paragraph", body: "Nos meninos, são avaliados o crescimento da genitália (G) e dos pelos pubianos (P). Cada um deles é dividido em cinco estágios, de 1 a 5. O estágio 1 indica que a puberdade ainda não começou, enquanto o estágio 5 representa o desenvolvimento físico completo. Os estágios 2, 3 e 4 mostram as mudanças que acontecem ao longo da puberdade (Marshall; Tanner, 1970)." },
    { type: "image", imageCaption: "Fonte: Brasil (2012a, p. 32-33)." },
  ],
  "transformacoes-menina": [
    { type: "paragraph", body: "Nas meninas, o primeiro sinal visível da puberdade é o surgimento do broto mamário, que corresponde ao início do desenvolvimento das mamas. Esse processo ocorre geralmente entre os 9 e 10 anos, podendo iniciar normalmente entre os 8 e os 13 anos. Em seguida, ou quase ao mesmo tempo, começam a surgir os pelos pubianos e inicia-se o estirão puberal, período em que ocorre o crescimento mais acelerado da altura, cujo pico costuma acontecer entre os 11 e 12 anos. O maior ganho de peso também ocorre, em geral, entre os 12 e 13 anos." },
    { type: "paragraph", body: "Após a menarca (primeira menstruação), o crescimento desacelera progressivamente." },
    { type: "paragraph", body: "Bacil et al. (2020); Krishna; Witchel (2024); Graber (2025)." },
    { type: "image", imageCaption: "Fonte: Brasil (2012b, p. 32-33)." },
    { type: "paragraph", body: "Nas meninas, são observados o crescimento das mamas (M) e dos pelos pubianos (P), classificados em cinco estágios, de 1 a 5. Assim como no caso dos meninos, o estágio 1 corresponde ao período antes do início da puberdade, enquanto o estágio 5 indica que o desenvolvimento físico foi concluído. Os estágios intermediários representam as diferentes mudanças que acontecem durante a puberdade (Marshall; Tanner, 1970; Krishna; Witchel, 2024)." },
  ],
  "menstruacao": [
    { type: "paragraph", body: "O amadurecimento dos órgãos reprodutores leva ao início da menstruação, chamada menarca. A menarca representa uma importante etapa do desenvolvimento reprodutivo feminino e ocorre, em média, por volta dos 12 anos, podendo acontecer normalmente entre os 9 e os 15 anos. Ela indica que o organismo está adquirindo capacidade reprodutiva." },
    { type: "paragraph", body: "Montenegro; Rezende Filho (2022); FEBRASGO (2017)." },
    { type: "image", imageCaption: "Fonte: Ilustração criada por inteligência artificial generativa (ChatGPT/OpenAI, 2025), baseada em Guyton; Hall (2021) e Krishna; Witchel (2024)." },
    { type: "paragraph", body: "O ciclo menstrual corresponde ao período entre o primeiro dia de uma menstruação e o primeiro dia da seguinte. Durante esse ciclo, os hormônios estimulam o amadurecimento do óvulo e sua liberação pelo ovário (ovulação). Após a ovulação, a progesterona prepara o útero para uma possível gravidez." },
    { type: "paragraph", body: "Caso a fecundação não ocorra — seja por não ter praticado relação sexual ou por ter usado um método contraceptivo, como a camisinha —, os níveis desses hormônios baixam, provocando a descamação do endométrio (camada interna do útero), que é eliminada pela vagina na forma de sangue, caracterizando a menstruação." },
    { type: "paragraph", body: "O fluxo menstrual costuma durar de 3 a 7 dias. Nos primeiros anos após a menarca, é comum que o ciclo menstrual varie entre 21 e 45 dias. Com o amadurecimento do organismo, tende a se tornar mais regular, variando geralmente entre 21 e 35 dias." },
    { type: "callout", heading: "Fique atenta...", body: "Nos primeiros anos após a menarca, é comum que o ciclo menstrual seja irregular, pois o organismo ainda está amadurecendo." },
    { type: "paragraph", body: "Montenegro; Rezende Filho (2022); SBP (2023a)." },
    { type: "callout", heading: "Você sabia...", body: "A precocidade ou atraso na ocorrência da menarca são influenciados por diversos fatores como a hereditariedade, fatores nutricionais, físicos, emocionais, exercício, gordura corporal e contexto social (Gemelli; Farias; Spritzer, 2020)." },
    { type: "callout", heading: "E tem mais...", body: "na adolescência, é possível engravidar antes mesmo da primeira menstruação. Por outro lado, também é comum que os primeiros ciclos menstruais sejam anovulatórios (ou seja, sem a liberação de um óvulo). Isso acontece porque o corpo ainda está passando por um amadurecimento hormonal e pode não produzir os picos de hormônios necessários para a ovulação. Por conta dessa imaturidade fisiológica natural da idade, a jovem pode apresentar ciclos irregulares e sangramentos inesperados, situações que fazem parte do ajuste normal do organismo nessa fase (SBP, 2023a)." },
    { type: "callout", heading: "Portanto recomenda-se...", body: "que a adolescente registre em um calendário as datas dos ciclos, ou seja: \"[...] a cada mês, o dia que inicia e o dia que termina o sangramento. Por exemplo: começou no dia 13 de janeiro e terminou no dia 17 [...]\" (Brasil, 2012b, p. 36)." },
    { type: "paragraph", body: "E ainda... existem aplicativos gratuitos que auxiliam no registro da menstruação, previsão da próxima menstruação, período fértil e sintomas relacionados ao ciclo." },
  ],
  "fecundacao": [
    { type: "paragraph", body: "A fecundação é o encontro do espermatozoide e do óvulo. Esse momento único marca o início da gestação e de um novo ser. Para que a fecundação aconteça, o corpo passa por uma sequência precisa de eventos:" },
    { type: "image" },
    { type: "quote_grid", items: ["Durante uma relação sexual desprotegida (sem o uso de um método contraceptivo), os espermatozoides presentes no sêmen são liberados dentro da vagina.", "Através dos movimentos de suas próprias caudas e contando com a ajuda das contrações naturais do útero, os espermatozoides sobem pelo aparelho genital feminino.", "Enquanto isso, o óvulo, que foi liberado pelo ovário na ovulação, é direcionado para a tuba uterina, onde fica aguardando.", "É exatamente ali, na tuba uterina, que os espermatozoides encontram o óvulo. Apenas um deles conseguirá romper a barreira do óvulo e entrar, completando a fecundação."] },
    { type: "paragraph", body: "(WHO, 2022)" },
  ],
  "metodos-contraceptivos": [
    { type: "paragraph", body: "Se o óvulo não encontrar um espermatozoide, os níveis dos hormônios progesterona e estrogênio diminuem. Essa queda dos hormônios faz com que o endométrio (camada interna do útero), que havia se preparado para receber uma possível gravidez, se desprenda e seja eliminado através do sangramento menstrual. Assim que a menstruação termina, o corpo recomeça um novo ciclo. Contudo, se a gravidez acontecer, o ciclo menstrual não se completa e segue o desenvolvimento da gestação (Montenegro; Rezende Filho, 2022)." },
    { type: "callout", heading: "Atenção...", body: "Para quem deseja ter relações sexuais, mas não quer engravidar, existem diversos métodos contraceptivos (ou anticoncepcionais), porém não existe um único método que sirva para todo mundo. Cada organismo é diferente, e alguns métodos podem ter contraindicações dependendo de cada pessoa. Por isso, o recomendado é escolher o que melhor se adapte às necessidades e à rotina de cada um. Além disso, independentemente do método, o que garante a menor chance de falha é o seu uso correto e consistente (WHO, 2022)." },
    { type: "image" },
  ],
  "classificacao-metodos": [
    { type: "paragraph", body: "Com a evolução da ciência, existem muitos métodos contraceptivos. Porém, nem todos estão disponíveis no Sistema Único de Saúde (SUS) e nem todos são indicados para adolescentes (como é o caso das cirurgias definitivas)." },
    { type: "paragraph", body: "Quanto à classificação, os métodos anticoncepcionais dividem-se em cinco grupos:" },
    { type: "list", items: ["De barreira: como as camisinhas masculina e feminina.", "Métodos de contracepção reversíveis de longa duração (LARC): Dispositivo intrauterino (DIU); Implante subdérmico de etonorgestrel (ISE).", "Hormonais: pílulas, injeções e adesivos.", "Definitivos: laqueadura e vasectomia (cirurgias).", "Comportamentais: incluem a tabelinha (Ogino-Knaus), o controle da temperatura basal, o exame do muco cervical (Billings), o método sintotérmico e o coito interrompido."] },
    { type: "callout", heading: "Olha só...", body: "os métodos comportamentais são pouco eficazes durante a adolescência, considerando que nessa fase de desenvolvimento muitas vezes não há regularidade no ciclo menstrual devido a mudanças hormonais, e os definitivos não são indicados para adolescentes — por isso, discutiremos sobre os demais." },
    { type: "paragraph", body: "SBP (2023b); Brasil (2022)." },
  ],
  "metodos-barreira": [
    { type: "paragraph", body: "Eles recebem esse nome porque criam uma barreira física que impede o espermatozoide de entrar no útero. Esse grupo inclui o diafragma, o capuz cervical, a esponja contraceptiva e os preservativos (camisinha) masculina e feminina." },
    { type: "callout", heading: "Fique ligado!!", body: "Os mais utilizados são os preservativos ou camisinha masculina e feminina, e são os únicos métodos que, além de evitar a gravidez, protegem contra as Infecções Sexualmente Transmissíveis (ISTs). Ambas são distribuídas gratuitamente em qualquer unidade de saúde do SUS, sem necessidade de receita médica." },
    { type: "heading", heading: "Camisinha masculina" },
    { type: "paragraph", body: "A camisinha masculina é um método contraceptivo de barreira, feito de látex ou outros materiais, que é colocado sobre o pênis ereto para evitar a gravidez e ajudar a prevenir as infecções sexualmente transmissíveis (ISTs)." },
    { type: "image", imageCaption: "Fonte: Ilustração elaborada por inteligência artificial generativa (ChatGPT/OpenAI, 2025), baseada em recomendações da World Health Organization (2022) e do Ministério da Saúde do Brasil (2022)." },
    { type: "heading", heading: "Como usar" },
    { type: "list", items: ["A camisinha deverá ser colocada assim que o pênis estiver ereto, antes de qualquer contato genital ou penetração.", "A ponta do preservativo (o reservatório) deverá ser apertada com os dedos para tirar o ar. Se o ar ficar ali dentro, o preservativo pode estourar durante a relação.", "Mantendo a ponta apertada, a camisinha deverá ser desenrolada da cabeça do pênis (glande) até a base.", "Para retirada segura, logo após a ejaculação, enquanto o pênis ainda estiver ereto, deverá ser retirado da vagina segurando firmemente a base da camisinha junto ao corpo para evitar que ela escorregue e o sêmen vaze."] },
    { type: "paragraph", body: "BRASIL (2022); WHO (2022)." },
    { type: "heading", heading: "Camisinha feminina" },
    { type: "paragraph", body: "A camisinha feminina também é um método contraceptivo de barreira, distribuído gratuitamente nas Unidades Básicas de Saúde e que não necessita de prescrição médica. É constituída por uma bolsa fina, flexível e resistente, com um anel em cada extremidade." },
    { type: "image", imageCaption: "Fonte: Ilustração elaborada por inteligência artificial generativa (ChatGPT/OpenAI, 2025), baseada nas recomendações da World Health Organization (2022) e do Ministério da Saúde do Brasil (2022)." },
    { type: "heading", heading: "Como usar" },
    { type: "list", items: ["O anel interno é introduzido na vagina para manter o preservativo posicionado, enquanto o anel externo permanece fora da vagina, cobrindo parcialmente a vulva.", "Durante a relação sexual, o preservativo impede o contato do pênis e do esperma com a mucosa vaginal, reduzindo o risco de gravidez e contribuindo para a prevenção das infecções sexualmente transmissíveis (ISTs).", "Após a relação sexual, o preservativo deve ser retirado cuidadosamente, evitando o extravasamento do sêmen, e descartado no lixo, não devendo ser reutilizado."] },
    { type: "paragraph", body: "BRASIL (2022); WHO (2022)." },
  ],
  "diu": [
    { type: "paragraph", body: "Os métodos contraceptivos de longa duração oferecem proteção eficaz contra a gravidez por vários anos, sem a necessidade de uso diário. São opções práticas, seguras e reversíveis, ou seja, a fertilidade pode retornar após sua retirada." },
    { type: "paragraph", body: "Dentre eles estão o Dispositivo Intrauterino (DIU) e o Implante subdérmico. O DIU é um pequeno objeto em formato de \"T\" colocado dentro do útero por um médico ou enfermeiro treinado. É um método de longa duração, extremamente seguro e muito recomendado para adolescentes por ser prático e não depender de esquecimentos. Existem dois tipos principais:" },
    { type: "quote_grid", items: ["DIU de Cobre: É totalmente gratuito e disponível para qualquer pessoa no SUS. Ele não possui hormônios, não impede a ovulação, mas cria um ambiente que inviabiliza o caminho dos espermatozoides. Tem validade de 10 anos.", "DIU Hormonal: Libera uma quantidade baixa de hormônio diretamente no útero, afinando a parede interna (endométrio) e engrossando o muco do colo do útero para impedir a entrada dos espermatozoides. Tem validade de 5 anos e está disponível no SUS apenas para casos médicos específicos."] },
    { type: "callout", heading: "Importante!", body: "Nenhum tipo de DIU protege contra Infecções Sexualmente Transmissíveis (ISTs). Por isso, o uso da camisinha continua sendo obrigatório em todas as relações." },
    { type: "callout", heading: "E ainda!", body: "Quando se orienta adolescentes quanto a métodos contraceptivos, deve-se apresentar todos os disponíveis, inclusive o DIU, pois os benefícios dos métodos intrauterinos extrapolam os riscos." },
    { type: "heading", heading: "O implante de etonorgestrel (ISE), conhecido comercialmente no Brasil como Implanon®" },
    { type: "paragraph", body: "Ele é um bastão bem pequeno e flexível implantado por profissional treinado debaixo da pele do braço. O procedimento é muito rápido e usa anestesia local. Ele impede que o corpo libere o óvulo, deixa o muco do útero grosso (o que bloqueia a entrada dos espermatozoides) e afina a parede interna do útero para evitar a gravidez. Este implante protege o corpo por até 3 anos seguidos. Se você quiser retirar antes desse tempo para engravidar ou mudar de método, pode pedir para tirar a qualquer momento. Para retirar, o profissional faz um corte minúsculo na pele, também com anestesia." },
    { type: "callout", heading: "Importante:", body: "Assim como o DIU, ele fica dentro do corpo, não tem como você esquecer de usar. Por isso, a chance de falha é quase zero." },
    { type: "paragraph", body: "SBP (2023b); WHO (2022). Fonte: Elaborado pela autora com auxílio do ChatGPT (OpenAI), 2026." },
  ],
  "metodos-hormonais": [
    { type: "paragraph", body: "Os anticoncepcionais trouxeram liberdade para as mulheres, porque permitem que elas planejem com segurança se e quando querem engravidar." },
    { type: "paragraph", body: "A maioria desses métodos são chamados de Anticoncepcionais Hormonais Combinados (AHC) porque juntam dois hormônios: o estrogênio e a progesterona." },
    { type: "heading", heading: "Como eles funcionam?" },
    { type: "paragraph", body: "A progesterona age fazendo com que o corpo não libere nenhum óvulo (um processo chamado de anovulação). Sem um óvulo disponível, o espermatozoide não tem quem fecundar e a gravidez simplesmente não acontece. Esses hormônios podem ser colocados no corpo de várias formas (como adesivos na pele, comprimidos ou injeções), mas o formato mais conhecido e utilizado no Brasil e no mundo é a chamada pílula anticoncepcional. Ela é um método reversível: isso significa que, se a mulher parar de tomar, o corpo volta a ovular normalmente e ela pode engravidar." },
    { type: "callout", heading: "Como você sabe...", body: "A pílula não protege contra Infecções Sexualmente Transmissíveis (ISTs). Para se proteger delas, o único método indicado é o uso da camisinha (masculina ou feminina) em todas as relações." },
    { type: "paragraph", body: "Para o sucesso da pílula, duas regras são fundamentais:" },
    { type: "list", items: ["Zero esquecimentos: ela precisa ser tomada todos os dias, de preferência rigorosamente no mesmo horário.", "Cuidado com outros remédios: alguns medicamentos podem cortar ou diminuir o efeito da pílula no organismo. Por isso, sempre avise ao médico ou dentista que você toma pílula antes de começar qualquer tratamento (FEBRASGO, 2025; SBP, 2023)."] },
    { type: "heading", heading: "Como usar?" },
    { type: "list", items: ["Primeira vez de uso: se a pílula for iniciada até o 5º dia da menstruação, a proteção contra a gravidez é imediata. Se for iniciada após esse período, ela também pode ser usada, desde que não haja gravidez, mas será necessário utilizar camisinha ou evitar relações sexuais durante os primeiros 7 dias.", "Troca de outro método hormonal: se o método anterior estava sendo utilizado corretamente e não há suspeita de gravidez, a pílula pode ser iniciada imediatamente, sem precisar esperar a próxima menstruação. Nesse caso, não é necessário utilizar um método de apoio.", "Troca do anticoncepcional injetável: a pílula pode ser iniciada na data em que seria aplicada a próxima injeção, sem necessidade de utilizar um método de apoio.", "Após usar a pílula do dia seguinte: a pílula anticoncepcional pode ser iniciada imediatamente, sem esperar a próxima menstruação. Quem já utilizava a pílula deve continuar a cartela normalmente. É necessário usar camisinha ou evitar relações sexuais durante os primeiros 7 dias."] },
    { type: "paragraph", body: "WHO (2022)." },
    { type: "heading", heading: "Anticoncepcional Injetável (Injeção)" },
    { type: "paragraph", body: "O anticoncepcional injetável é um método contraceptivo prático e eficaz para quem prefere não precisar tomar um comprimido todos os dias. Existem dois tipos: o mensal e o trimestral. A aplicação é feita por um profissional de saúde, geralmente no músculo do braço ou do glúteo, e ambas são fornecidas pelo SUS." },
    { type: "heading", heading: "Como usar?" },
    { type: "list", items: ["Primeira dose: recomenda-se que seja aplicada nos primeiros sete dias da menstruação. Nessa situação, a proteção contra a gravidez é imediata.", "Se a aplicação ocorrer após esse período: a injeção pode ser iniciada desde que haja certeza de que não existe gravidez. Nesse caso, recomenda-se utilizar preservativo ou evitar relações sexuais durante os primeiros sete dias, até que o método atinja sua eficácia contraceptiva."] },
    { type: "paragraph", body: "WHO (2022); SBP (2023b)." },
    { type: "callout", heading: "Atenção", body: "Quando as mulheres utilizam anticoncepcionais injetáveis trimestrais, implante hormonal ou DIU hormonal e desejam fazer a troca por pílulas anticoncepcionais, devem iniciar a cartela imediatamente após o término da validade do método usado anteriormente. Com relação ao intervalo entre as cartelas, alguns contraceptivos preveem pausas de quatro a sete dias e algumas formulações não preveem pausas." },
    { type: "callout", heading: "Importante lembrar!", body: "Os comprimidos devem ser ingeridos diariamente e preferencialmente no mesmo horário. O esquecimento do uso implica em falha contraceptiva; nesse caso, recomenda-se o uso de método contraceptivo adicional, como preservativos." },
    { type: "paragraph", body: "FEBRASGO (2025); SBP (2023b)." },
    { type: "paragraph", body: "Também existem outros dispositivos hormonais, são eles:" },
    { type: "heading", heading: "Anel Vaginal" },
    { type: "paragraph", body: "É um anel de plástico bem flexível e macio que libera hormônios no corpo, impedindo a ovulação." },
    { type: "paragraph", body: "Como usar: você mesma coloca e retira o anel de dentro da vagina. Ele deve ficar lá dentro por 3 semanas seguidas. Na 4ª semana, você tira o anel para fazer uma pausa (que é quando a menstruação desce) e depois coloca um anel novo. É discreto, regula o ciclo e não altera em nada a saúde da sua região íntima." },
    { type: "paragraph", body: "FEBRASGO (2025); SBP (2023b)." },
    { type: "heading", heading: "Adesivo Anticoncepcional" },
    { type: "paragraph", body: "É um adesivo que vai soltando hormônios direto na corrente sanguínea para bloquear a ovulação. É bem fino e colante, você gruda na pele (pode ser no braço, nas costas ou na barriga) e troca por um novo uma vez por semana, durante 3 semanas. A 4ª semana é livre de adesivo (a semana de pausa para menstruar)." },
    { type: "paragraph", body: "É um método moderno e seguro, bom para quem esquece de tomar remédio todo dia. Porém, como ele fica colado na pele, fica visível, o que algumas adolescentes podem não curtir. Pode causar uma leve coceira ou irritação na pele onde foi colado." },
    { type: "paragraph", body: "FEBRASGO (2025); SBP (2023b)." },
    { type: "heading", heading: "Contracepção de emergência (pílula do dia seguinte)" },
    { type: "paragraph", body: "A pílula do dia seguinte é um método para ser usado apenas em emergências — como quando a camisinha estoura, sai do lugar ou você esquece de tomar o anticoncepcional comum. Para que ela funcione e evite uma gravidez, o tempo é o fator mais importante." },
    { type: "callout", heading: "Atenção", body: "O ideal é tomar a pílula o mais rápido possível. Se você tomar nas primeiras 12 a 24 horas após a relação desprotegida, a eficácia dela é máxima. O prazo da bula (até 3 dias): a bula do medicamento garante o funcionamento seguro se tomado em até 72 horas (3 dias) após a relação. O limite máximo (até 5 dias): a Organização Mundial da Saúde (OMS) afirma que a pílula ainda pode funcionar se tomada em até 120 horas (5 dias). Mas atenção: a chance de o remédio falhar aumenta drasticamente a cada dia que passa. Se você deixar para tomar depois do terceiro dia, o risco de engravidar é bem maior. Lembre-se: ela se chama pílula \"do dia seguinte\" — quanto mais você demorar para tomar, menor será o efeito dela no organismo!" },
    { type: "paragraph", body: "SBP (2023b)." },
    { type: "callout", heading: "Olha só...", body: "O adolescente tem direito à educação sexual, ao acesso à informação sobre contracepção, à confidencialidade, ao sigilo sobre sua atividade sexual e à prescrição de métodos anticoncepcionais (FEBRASGO, 2017, p. 13). Nenhum método contraceptivo (com exceção dos métodos definitivos) deve ser contraindicado tendo como única base a idade. Por outro lado, a falta de conhecimento, aconselhamento inadequado, mitos e moralidade em relação à sexualidade são comuns e interferem na escolha e no uso do método (FEBRASGO, 2017, p. 15)." },
  ],
  "mitos-anticoncepcional": [
    { type: "quote_grid", items: ["É verdade que o anticoncepcional engorda? Não exatamente. Estudos científicos mostram que as pílulas anticoncepcionais não causam ganho de gordura. A única exceção importante é a injeção anticoncepcional de três meses, que por ser uma dose mais concentrada, pode causar ganho de peso real (geralmente entre 2 kg e 3 kg).", "O anticoncepcional ajuda a melhorar a acne (espinhas)? Sim, é verdade para os anticoncepcionais hormonais combinados! As pílulas reduzem a oleosidade da pele e do couro cabeludo, ajudando muito a controlar cravos e espinhas.", "Existem outros benefícios além de evitar a gravidez? Com certeza. Além de prevenir a gravidez, a pílula pode trazer outros benefícios, como melhorar a acne, diminuir as cólicas, reduzir o fluxo menstrual, ajudar a manter a menstruação mais regular e aliviar alguns sintomas da TPM, como o inchaço e a irritabilidade. Além disso, seu uso também está associado à redução do risco de alguns tipos de câncer, como o de ovário e o de endométrio."] },
    { type: "heading", heading: "Fique por dentro!" },
    { type: "list", items: ["A pílula anticoncepcional não se acumula no organismo.", "A pílula deve ser tomada diariamente.", "O uso da pílula não causa infertilidade.", "A pílula não causa malformações no bebê.", "A pílula não aumenta a chance de gravidez gemelar (gêmeos).", "A pílula não altera, por si só, o desejo sexual.", "A pílula não interrompe uma gravidez já existente."] },
    { type: "paragraph", body: "FEBRASGO (2025); WHO (2022)." },
  ],
  "direitos-sexuais-reprodutivos": [
    { type: "paragraph", body: "As pessoas têm o direito de decidir se desejam ou não uma gestação, em que momento ela deve acontecer e quantos filhos querem ter. Para que esse direito seja exercido de forma consciente e responsável, é necessário o conhecimento sobre as formas e os dispositivos existentes com o objetivo de evitar esse evento. Como resultado de reivindicações coletivas, emergiu a noção de direitos à saúde sexual e reprodutiva, sendo definidos os direitos sexuais como a \"[...] possibilidade de viver e expressar livremente a sexualidade sem violência, discriminações e imposições [...]. O direito do sexo seguro para prevenção da gravidez e de doenças sexualmente transmissíveis (DST) e Aids\" (BRASIL, 2010, p. 16). Os direitos reprodutivos referem-se à possibilidade \"[...] de acesso a informações, meios, métodos e técnicas para ter ou não filhos\" (BRASIL, 2010, p. 15). Nesse sentido, deve ser garantido a todos os sujeitos sociais (adultos, jovens e adolescentes), de forma equitativa, os direitos sexuais e reprodutivos, como expressão do acesso integral à saúde." },
  ],
  "gravidez-adolescencia-mudancas": [
    { type: "paragraph", body: "Após a fecundação, o corpo feminino passa por uma série de transformações fisiológicas. Cada mulher percebe essas mudanças de maneira única, o que pode gerar sentimentos de vulnerabilidade física e emocional durante a gestação (Alves; Bezerra, 2020)." },
    { type: "paragraph", body: "Essas fases são divididas em períodos marcantes:" },
    { type: "quote_grid", items: ["1º Trimestre: É marcado por intensas transformações hormonais para sustentar a gravidez. Surgem sintomas como a interrupção da menstruação, mudanças no sono e no apetite, aumento das mamas e do volume de sangue, além de enjoos e vômitos.", "2º Trimestre: É uma fase de adaptação mais confortável. O útero cresce visivelmente, a mãe começa a sentir os movimentos do bebê e o peito inicia a produção do colostro (o primeiro leite).", "3º Trimestre: O bebê cresce de forma acelerada. O tamanho do útero passa a pressionar os outros órgãos da mãe, o que costuma causar desconfortos como dor nas costas (lombar), falta de ar, azia e refluxo.", "Puerpério (Pós-parto): Após o nascimento do bebê, o corpo entra em um período de recuperação física profunda, marcado pelo início de novas experiências desafiadoras e afetuosas, como a amamentação."] },
    { type: "paragraph", body: "Castilho; Mattos; Pedrosa (2024)." },
  ],
  "orientacao-quem-pode-ajudar": [
    { type: "callout", heading: "É fundamental…", body: "Você não precisa passar por isso sozinho. Conversar em casa sobre as transformações do corpo, os sentimentos, os medos e as inseguranças é fundamental para atravessar essa fase com mais leveza e segurança." },
    { type: "paragraph", body: "Procure o posto de saúde: as unidades de saúde (os postos de saúde) são o principal ponto de apoio para esse momento. O enfermeiro e a equipe de saúde estão ali para acolher você. Eles oferecem consultas, distribuem e orientam sobre métodos contraceptivos e conversam abertamente sobre direitos sexuais e reprodutivos, garantindo que você tome decisões informadas e seguras sobre o seu futuro." },
  ],
  "referencias": [
    { type: "list", items: ["ALVES, T. V.; BEZERRA, M. M. M. Principais alterações fisiológicas e psicológicas durante o período gestacional. Rev. Mult. Psic., Jaboatão dos Guararapes, v. 14, n. 49, p. 114-126, fev. 2020. Disponível em: https://idonline.emnuvens.com.br/id/article/view/2324/3608#. Acesso em: 06 jun. 2026.", "BRASIL. Ministério da Saúde. Secretaria de Atenção à Saúde. Departamento de Ações Programáticas Estratégicas. Diretrizes nacionais para a atenção integral à saúde de adolescentes e jovens na promoção, proteção e recuperação da saúde. Brasília: Ministério da Saúde, 2010. Disponível em: http://bvsms.saude.gov.br/bvs/publicacoes/diretrizes_nacionais_atencao_saude_adolescentes_jovens_promocao_saude.pdf. Acesso em: 9 jul. 2026.", "BRASIL. Ministério da Saúde. Secretaria de Atenção à Saúde. Departamento de Ações Programáticas Estratégicas. Caderneta de saúde do adolescente: menino. Brasília: Ministério da Saúde, 2012a. Disponível em: https://saude.rs.gov.br/upload/arquivos/carga20190754/10135428-caderneta-saude-adolescente-menino.pdf. Acesso em: 1 jul. 2026.", "BRASIL. Ministério da Saúde. Secretaria de Atenção à Saúde. Departamento de Ações Programáticas Estratégicas. Caderneta de saúde do adolescente: menina. Brasília: Ministério da Saúde, 2012b. Disponível em: https://saude.rs.gov.br/upload/arquivos/carga20190755/10135513-caderneta-saude-adolescente-menina.pdf. Acesso em: 1 jul. 2026.", "BRASIL. Ministério da Saúde. Protocolo clínico e diretrizes terapêuticas para atenção integral às pessoas com infecções sexualmente transmissíveis (IST). Brasília: Ministério da Saúde, 2022. Disponível em: https://www.gov.br/aids/pt-br/central-de-conteudo/pcdts/2022/ist/pcdt-ist-2022_isbn-1.pdf/@@display-file/file. Acesso em: 7 jul. 2026.", "BRASIL. Lei nº 8.069, de 13 de julho de 1990. Dispõe sobre o Estatuto da Criança e do Adolescente e dá outras providências. 13. ed. Brasília: Senado Federal, 2017. Disponível em: https://www2.senado.leg.br/bdsf/bitstream/handle/id/534718/eca_1ed.pdf. Acesso em: 9 jul. 2026.", "BRASIL. Ministério da Saúde. Secretaria de Atenção Primária à Saúde. Manual técnico de anticoncepção. Brasília: Ministério da Saúde, 2022. Disponível em: https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/s/saude-da-mulher/saude-sexual-e-reprodutiva/contracepcao. Acesso em: 12 jul. 2026.", "CASTILHO, S. B.; MATTOS, V. G. da S.; PEDROSA, L. G. B. Impactos físicos e emocionais da gestação na adolescência: uma revisão de literatura. Revista Foco, [S. l.], v. 17, n. 5, p. e4934, 2024. Disponível em: https://ojs.focopublicacoes.com.br/foco/article/view/4934. Acesso em: 22 jun. 2026.", "FEDERAÇÃO BRASILEIRA DAS ASSOCIAÇÕES DE GINECOLOGIA E OBSTETRÍCIA (FEBRASGO). Anticoncepção para adolescentes. São Paulo: Connexomm, 2017. (Série Orientações e Recomendações FEBRASGO, n. 9). Disponível em: https://www.febrasgo.org.br/media/k2/attachments/15-ANTICONCEPCAO_PARA_ADOLESCENTES.pdf. Acesso em: 11 jul. 2026.", "FEDERAÇÃO BRASILEIRA DAS ASSOCIAÇÕES DE GINECOLOGIA E OBSTETRÍCIA (FEBRASGO). Anticoncepção hormonal combinada. Femina, [S. l.], v. 53, n. 12, p. 1382-1389, 2025. Disponível em: https://femina.org.br/wp-content/uploads/sites/12/articles_xml/0100-7254-femina-53-12-1382/0100-7254-femina-53-12-1382.pdf. Acesso em: 12 jul. 2026.", "FINOTTI, M. C. C. F. Manual de anticoncepção. São Paulo: Federação Brasileira das Associações de Ginecologia e Obstetrícia (FEBRASGO), 2015. Disponível em: https://portaldeboaspraticas.iff.fiocruz.br/biblioteca/manual-de-anticoncepcao. Acesso em: 5 jul. 2026.", "GEMELLI, I. F. B.; FARIAS, E. S.; SPRITZER, P. M. Associação da composição corporal e idade da menarca em meninas e adolescentes na Amazônia Brasileira. Jornal de Pediatria, Porto Alegre, v. 96, n. 2, p. 240-246, mar./abr. 2020. Disponível em: https://www.scielo.br/scielo.php?pid=S0021-75572020000200240&script=sci_arttext&tlng=pt. Acesso em: 3 jul. 2026.", "GRABER, E. G. Physical Growth and Sexual Maturation of Adolescents. MSD Manual Professional Edition, [S. l.], jan. 2025. Disponível em: https://www.msdmanuals.com/professional/pediatrics/growth-and-development/physical-growth-and-sexual-maturation-of-adolescents. Acesso em: 3 jul. 2026.", "GUYTON, A. C.; HALL, J. E. Tratado de Fisiologia Médica. 14. ed. Rio de Janeiro: Elsevier, 2021.", "KRISHNA, K. B.; WITCHEL, S. F. Puberdade normal e anormal. In: FEINGOLD, K. R. et al. (ed.). Endotext. South Dartmouth: MDText.com, 2024. Disponível em: https://www.ncbi.nlm.nih.gov/books/NBK279024/#norm-abnorm-puberty.STAGING_OF_PUBERTY. Acesso em: 3 jul. 2026.", "MARSHALL, W. A.; TANNER, J. M. Variations in the pattern of pubertal changes in boys. Archives of Disease in Childhood, [S. l.], v. 45, n. 239, p. 13-23, fev. 1970. Disponível em: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2020414/. Acesso em: 3 jul. 2026.", "ORGANIZAÇÃO MUNDIAL DA SAÚDE. Family planning: a global handbook for providers: evidence-based guidance developed through worldwide collaboration. 4. ed. Genebra: Organização Mundial da Saúde, 2022. Disponível em: https://fphandbook.org/. Acesso em: 7 jul. 2026.", "REZENDE FILHO, Jorge de; MONTENEGRO, Carlos Antonio. Rezende obstetrícia fundamental. 14. ed. Rio de Janeiro: Guanabara Koogan, 2022.", "SARTOR, B. C.; FIORIN, P. B. G.; SULZBACHER, M. M. Infância acelerada: a complexidade da puberdade precoce e a importância do acompanhamento clínico. Revista DELOS, Curitiba, v. 18, n. 74, p. 1-22, 2025. DOI: https://doi.org/10.55905/rdelosv18.n74-044. Disponível em: https://ojs.revistadelos.com/delos/article/view/2347. Acesso em: 20 jun. 2026.", "SOCIEDADE BRASILEIRA DE PEDIATRIA. Departamento Científico de Medicina do Adolescente (gestão 2022-2024). Como reconhecer um ciclo menstrual normal em adolescentes? Rio de Janeiro: Sociedade Brasileira de Pediatria, 2023a. (Guia Prático de Atualização). Disponível em: https://www.sbp.com.br/fileadmin/user_upload/24065c-GPA_-_ComoReconhecer_CicloMenstrual_Nl_em_Adl.pdf. Acesso em: 7 jul. 2026.", "SOCIEDADE BRASILEIRA DE PEDIATRIA. Departamento Científico de Adolescência. Contracepção na adolescência: o que há de novo? Rio de Janeiro: Sociedade Brasileira de Pediatria, 2023b. (Guia Prático de Atualização). Disponível em: https://www.sbp.com.br/fileadmin/user_upload/24200f-GPA_ISBN-_Atualiza_MetodosEfetivos_Contracepcao_Adl.pdf. Acesso em: 1 jul. 2026."] },
  ],
};